서블릿 예외

서블릿은 2가지 방식으로 예외 처리를 지원한다.
* `Exception`
* `response.sendError(HTTP 상태코드, 오류 메시지`

### Exception
자바 직접 실행
자바의 메인 메서드를 직접 실행하는 경우 `main`이라는 쓰레드가 실행된다.
실행 도중에 예외를 잡지 못하고 처음 실행한 `main()` 메서드를 넘어서 예외가 던져지면, 
예외정보를 남기고 해당 쓰레드는 종료된다. 

메서드를 호출하면 메서드를 호출한 상위 메서드로 예외를 계속 던지게 된다.

*웹 애플리케이션*

웹 애플리케이션은 사용자 요청별로 별도의 쓰레드가 할당되고, 서블릿 컨테이너 안에서 실행된다.
애플리케이션은 예외가 발생했는데, 어디선가 try-catch 예외로 잡아서 처리하면 아무런 문제가 없다.
하지만, 만약 애플리케이션에서 예외를 잡지못하고, 서블릿 밖으로 까지 예외가 전달되면 어떻게 동작할까?
즉, 호출한 쪽(상위메서드)으로 계속 예외가 던져지고 있는 상황!!

```java
WAS(여기까지) <- 필터 <- 서블릿 <- 인터셉터 <- 컨트롤러(예외발생)
```